### PR TITLE
Sublime Text 3

### PR DESCRIPTION
**Pull request by KristoforMaynard**
Add support for the latest Sublime Text 3 beta.

### CODE REVIEW

**Comment by KristoforMaynard** [comment]
Oops, I didn't actually read the open issues when I submitted my pull request. I incorporated nfaggian's python3 friendly changes to string formatting, and vapesk's changes for the icon paths. In my tests, this works with both ST2 and ST3 - no need for a separate branch.

**Comment by dan-blanchard** [comment]
FYI, displaying the list of errors will not work in ST3 with this because line 240 in pylinter.py uses the `unicode` type, which is not part of Python 3. A simple work around would be to add the following at the top:

``` python
import sys
if sys.version_info >= (3,):
    unicode = str
```

**Comment by KristoforMaynard** [comment]
Good catch. Unfortunately that doesn't quite fix the unicode problem. Since python3 saw str(value, errors="ignore"), it was trying to decode a str object (value), which it didn't like. I added a check for python 3 at the offending line, but this is really not elegant. I'm guessing there's more to the unicode story, but I don't have anything to test that would require unicode support, so I will let someone that cares more about it chime in.

**Comment by dan-blanchard** [comment]
The reason my suggestion didn't work was because I did not realize that the current implementation was using a call to unicode that many would consider bad style. One should not use

``` python
unicode(value, errors="ignore")
```

but rather

``` python
value.decode(errors="ignore")
```

That said, I don't actually think that entire part is even necessary because decoding should already have taken place on lines 364 and 365.

I would suggest changing

``` python
from __future__ import print_function
```

to

``` python
from __future__ import print_function, unicode_literals
```

to make string literals work the same way in Python 2 and Python 3. That should help identify more of these gotchas more quickly.

**Pull request closed without merging**
