### PR TITLE
Issue #34 actual workaround keeping the globals

### PR DESCRIPTION
**Pull request by daogilvie-9fin**
Removed early call to API, settings now loaded only when API ready. Still a lot of globals. Will perhaps continue this fork to get rid of them. Tested and confirmed to work on OS X 10.9 with Homebrew python 3 and 2.7 for external Pylint.

I also ran Pylint on the file and changed a few things. Not all of the things though.

### CODE REVIEW

**Comment by biermeester** [comment]
I'll have a closer look at your patch tonight and probably merge it too. Thank you very much!

**Comment by daogilvie-9fin** [comment]
No problem. I may have added to it by then, as I appear to have caused some trouble with the lint-on-save mechanism, though I don't remember if it was working before. :$

**Comment by daogilvie-9fin** [comment]
Yeah, the background linter is still being created before the settings are available. Working on it.

**Comment by daogilvie-9fin** [comment]
All should work now. Hopefully I've not made too much of a mess :)

**Comment by biermeester** [comment]
I tried your patch on a fresh Pylinter install, but I got errors when SublimeText launched. Those errors might have been already there though, from before the patch. For now, I just tweaked the code so no exceptions are thrown.

Do you have the exact same problem as mentioned in #34 ? In that case a quick workaround is to launch SublimeText from the virtualenv that has Pylint installed.

If your problem is different, please elaborate.

**Comment by daogilvie-9fin** [comment]
My error was the same, yes. I do use virtualenvs, but I'm quite new to them so it might be that it confused my testing of the problem. I don't use pylint in the virtualenv, I have it installed on the system-wide general python, and my patch works with that set up. Sorry for confusing the situation! I have changed the check for the settings load to a more sensible choice of variable, which may have caused the errors you mentioned. I think I have a few things to learn about testing.

**Comment by biermeester** [comment]
I've incorporated some of you ideas into the latest version. Thanks for you feedback!

**Comment by daogilvie-9fin** [comment]
No problem. It's the first bit of serious python I've done and looking at how you've incorporated the changes is actually quite informative! Looks like I've got a lot to learn still, but I'm glad it was at least a little useful.

**Pull request closed without merging**
